name: My First Workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 
             
        - name: List and Read File
          run: |
            echo "My first github actions task"
            ls -ltra
            cat README.md
        
        - name: Generate ASCII art work
          run: cowsay -f dragon "Run for cover, I am a DRAGON ...... ROARRRR" >> dragon.txt

        # - name: List files
        #   run: ls
        
        # - name: Read the file
        #   run: cat README.md