name: Generate ASCII ARTWORK

on: push

jobs:
    build_job_1: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 
             
        - name: Install Cowsay library
          run: sudo apt-get install cowsay -y

        - name: List the files
          run: ls -ltra

        - name: Run the script file
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh 

    test_job_2: 
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Find the file
          run: grep -i "dragon" dragon.txt

    deploy_job_3: 
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Read the file
          run: cat dragon.txt


        # - name: Generate ASCII art work
        #   run: cowsay -f dragon "Run for cover, I am a DRAGON ...... ROARRRR" >> dragon.txt

        # - name: Test if file exists
        #   run: grep -i "dragon" dragon.txt
        
        # - name: Read the text file
        #   run: cat dragon.txt
        
        # - name: List and Read File
        #   run: |
        #     echo "My second github actions task"
        #     ls -ltra

        # - name: List files
        #   run: ls
        
        # - name: Read the file
        #   run: cat README.md