name: Generate ASCII ARTWORK

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 
             
        - name: Install Cowsay library
          run: sudo apt-get install cowsay -y

        
        - name: Generate ASCII art work
          run: cowsay -f dragon "Run for cover, I am a DRAGON ...... ROARRRR" >> dragon.txt

        - name: Test if file exists
          run: grep -i dragon.txt
        
        - name: Read the text file
          run: cat dragon.txt
        
        - name: List and Read File
          run: |
            echo "My second github actions task"
            ls -ltra

        # - name: List files
        #   run: ls
        
        # - name: Read the file
        #   run: cat README.md